### ISSUE TITLE
`defineProps().withDefault()` chain call

### ISSUE THREAD

**Issue by sxzz** [sxzz/vue-macros#214]
feature name: `chainCall`

**Comment by AlanLes** [comment]
Hello, it seems interesting as a first issue for new contributors; can I take this one on me? 🙂

**Comment by sxzz** [comment]
@AlanLes Unfortunately this feature is done and implemented already in PR #231

If you are interested, you can take another issue or raise an issue about a new feature request.

**Comment by unshame** [comment]
After trying out reactive props destructuring and being disappointed by how awkward it is to pass props into composables with it, I really hope this one gets merged, so I can use it instead.
