### ISSUE TITLE
Importing `package.json` and using `better-define` throws SyntaxError

### ISSUE THREAD

**Issue by zam157** [sxzz/vue-macros#381]
### Describe the bug

After updating `vue-macros` version to `2.2.0`, importing `package.json` and using `better-define` throws SyntaxError
![image](https://github.com/sxzz/vue-macros/assets/24277775/2d8f82b3-8aac-4c53-b939-4d8cd8ecd40d)

### Reproduction

https://stackblitz.com/edit/github-pwbvmq?file=src%2FApp.vue

### System Info

```Shell
CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
    Memory: 4.48 GB / 15.70 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.50)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Released as `unplugin-vue-macros@2.2.1`
