### ISSUE TITLE
Failed to resolve types

### ISSUE THREAD

**Issue by OrbisK** [sxzz/vue-macros#387]
### Describe the bug

```
vite.config.ts:15:23 - error TS2307: Cannot find module 'unplugin-vue-macros/vite' or its corresponding type declarations.

15 import VueMacros from 'unplugin-vue-macros/vite'

```

### Reproduction

https://github.com/antfu/vitesse/blob/main/vite.config.ts#LL17C21-L17C44

### System Info

```Shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 31.81 GB / 63.78 GB
  Binaries:
    Node: 20.2.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (113.0.1774.50)
    Internet Explorer: 11.0.22000.120
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
See https://github.com/sxzz/vue-macros/discussions/336#discussion-5071102
