### ISSUE TITLE
Reactivity Transform prop alias not usable in template

### ISSUE THREAD

**Issue by rashfael** [sxzz/vue-macros#401]
### Describe the bug

I'm using `vue@3.3` and `@vue-macros/reactivity-transform` to try to get my existing projects that used `vue@3.2` and reactivity transform to work.

When aliasing a prop when destructuring like so:
```js
const {
  prop1: propAlias
} = defineProps(…);
```
it can't be used in the template and you get a warning:
```
Property "propAlias" was accessed during render but is not defined
```

I did some digging and `@vue/compiler-sfc` relies on `bindingMetadata` being filled with information from the script when compiling the template to resolve for example prop aliases.
In `vue@3.3` destructured prop aliases are now set [here](https://github.com/vuejs/core/blob/124160e417015ed55afc2e7a9207429ff4eaebb4/packages/compiler-sfc/src/script/definePropsDestructure.ts#L51), with the new destructureProps feature.

Other pieces of `bindingMetadata` are also missing, but I'm not sure which effects those have. Some are set [here](https://github.com/vuejs/core/blob/124160e417015ed55afc2e7a9207429ff4eaebb4/packages/compiler-sfc/src/script/defineProps.ts#L178). It looks like adding the `__MACROS_mergeDefaults` shim breaks detection of props in this case.

My current hack is not transforming the `defineProps` statement at all by removing [this call](https://github.com/sxzz/vue-macros/blob/main/packages/reactivity-transform/src/core/index.ts#L131) and enabling `propsDestructure` in `vue@3.3`, which will then basically just set the `bindingMetadata` and replace nothing else (apart from maybe handling destructure defaults), because all uses of props in `script` have already been replaced by `vue-macros`.

Doing this makes `vue-macros` rely on `propsDestructure` being enabled in vue, so I don't know if this is the ideal solution.

_Using just `vue@3.3` with the deprecated reactivity transform results in the uses of the destructured props being transformed by the new props destructure feauture instead of the "old" reactivity transform, which makes them vulnerable to the drawbacks mentioned in the RFC https://github.com/vuejs/rfcs/discussions/502. Especially calling `$$` on a destructured prop does nothing anymore in `vue@3.3`_

### Reproduction

https://stackblitz.com/edit/vitejs-vite-v8ksvs?file=src%2Fcomponents%2FHelloWorld.vue

### System Info

```Shell
System:
    OS: Linux 6.3 Arch Linux
    CPU: (16) x64 AMD Ryzen 7 PRO 6850H with Radeon Graphics
    Memory: 13.89 GB / 30.62 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Chromium: 114.0.5735.133
    Firefox: 114.0.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Thanks for your detailed issue. Fixed and please the next release. ❤️

**Comment by rashfael** [comment]
Thanks for the fix, I just tested it with my project and it works! :heart:
