### ISSUE TITLE
Corresponding file is not included in tsconfig.json 

### ISSUE THREAD

**Issue by Charlee-du** [sxzz/vue-macros#405]
### Describe the bug

使用webstorm工具时，页面使用defineOptions会提示Corresponding file is not included in tsconfig.json
<img width="1175" alt="image" src="https://github.com/sxzz/vue-macros/assets/37035916/107e88a1-26ff-4e41-8e88-68daa7b5572a">
<img width="774" alt="image" src="https://github.com/sxzz/vue-macros/assets/37035916/6935274b-e08c-4f04-8158-286a09e5e5ab">

### Reproduction

1.3.8

### System Info

```Shell
Corresponding file is not included in tsconfig.json
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by txfyteen** [comment]
I solved it by manual import defineProps .
import { ref, + defineProps } from "vue";

defineProps<{ msg: string }>();
Do you have any other way？
